# Gaussian Naive Bayes Classifier

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

import numpy as np

In [ ]:
X,y= load_iris(return_X_y=True)

In [ ]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=1)

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
clf=GaussianNB()
clf

GaussianNB()

In [ ]:
clf.fit(X_train,y_train)

GaussianNB()

In [ ]:
clf.predict(X_test)

array([0, 1, 1, 0, 2, 2, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 1, 2,
       1])

In [ ]:
clf.score(X_test,y_test)

0.9333333333333333

In [ ]:
clf.predict_proba(X_test)

array([[1.00000000e+000, 7.30172724e-017, 1.92698897e-023],
       [1.83127445e-031, 9.99999349e-001, 6.50949259e-007],
       [6.64026638e-099, 9.71309470e-001, 2.86905301e-002],
       [1.00000000e+000, 4.50426332e-015, 5.93894621e-022],
       [1.24729705e-266, 1.50022255e-009, 9.99999998e-001],
       [1.25848413e-120, 4.97361143e-001, 5.02638857e-001],
       [8.22548006e-192, 6.90370263e-007, 9.99999310e-001],
       [1.00000000e+000, 3.05551312e-011, 3.69926602e-018],
       [1.00000000e+000, 1.34176387e-015, 8.87395065e-023],
       [1.55475502e-229, 2.00287031e-008, 9.99999980e-001],
       [4.44110262e-082, 9.99584753e-001, 4.15247469e-004],
       [1.00000000e+000, 8.14093994e-013, 1.12264893e-019],
       [1.14065997e-230, 2.17224776e-007, 9.99999783e-001],
       [1.44834682e-106, 8.84361311e-001, 1.15638689e-001],
       [2.27759005e-105, 9.66946340e-001, 3.30536601e-002],
       [1.00000000e+000, 2.98417907e-017, 1.87295578e-024],
       [1.26088164e-070, 9.99923670e-001